# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_by',
            field=models.CharField(default='blbejan', max_length=50),
            preserve_default=False,
        ),
    ]
